### PR TITLE
Fix a few pipelining bugs with RSP

### LINKED ISSUE #155: RSP: break should not have a delay slot
break should prevent any further instructions from executing, currently it seems to still execute at least some part of the next instruction, for example:

```
  li t0, 1
  sw t0, addr (r0)
  break
  sw r0, addr (r0)
```

The second store takes effect. I'll put together a test ROM to demonstrate.

### PR DESCRIPTION
**Pull request by rasky**
1) Setting SP_PC was not resetting the pipeline. This caused that
changing the PC within a HALT/UNHALT sequence was still causing
previous instructions in the pipeline (at the old address) to be
executed. This is not how the hardware works: SP_PC is immediate and
discards the whole pipeline.

2) BREAK did not correctly halt the processor at the right instruction,
which in turn caused resumption after HALT to execute the wrong
set of instructions. This was caused by the fact that the SP_STATUS
change was written into the EXDF latch, which in turn takes 3 cycles
to reach completion. Instead, we now use the DFWB latch, and we cause
it to abort the RSP cycle if the processor is halted. This happens
at the beginning of next cycle, which is the correct moment.

2) Since we are at it, use rsp_status_write to modify the RSP in
this case, rather than a direct write to the register. This change
fixes a race condition: SP_STATUS must be accessed atomically when
cen64 runs in multithreaded mode. To use rsp_status_write, we need
to introduce a nonexisting SP_SET_BROKE bit: we use the MSB, but then
mask it out in MTC0 to avoid some code to inadvertently have that bit
set.

3) When unhalting after BREAK, it's important to keep the correct
PC which comes from the EX stage (the one that was going to be
executed if BREAK didn't occur). Before, it was using the IF PC (fetch)
which is farther in the future.

Fixes #155

### CODE REVIEW

File: rsp/interface.c [hunk 1]
```diff
@@ -175,8 +175,20 @@ int write_sp_regs2(void *opaque, uint32_t address, uint32_t word, uint32_t dqm)
...
-  if (reg == SP_PC_REG)
+  if (reg == SP_PC_REG) {
+    // Setting the SP PC registers from the CPU basically forces the RSP to
+    // start from there, irrespective of existing pipeline stages, so we need
+    // to reset the pipeline.
+    // NOTE: this is currently broken when using multithreading if the CPU
+    // sets the PC while the RSP is running, so we just abort in this case
+    // which should not happen anyway in real world.
+    if (!(rsp->regs[RSP_CP0_REGISTER_SP_STATUS] & SP_STATUS_HALT)) {
+      printf("SP PC set while the RSP is running\n");
```
Comment (sp1187) [inline rsp/interface.c:186]: The `assert(0 && "message")` is fairly common in the current codebase, might change for consistency.

Comment (rasky) [reply rsp/interface.c]: Done
